name: "Flask Dashboard"
version: "1.0"
slug: "flask_dashboard"
description: "ASCII + SVG dashboard"
startup: "services"
boot: "auto"
ports:
  "3000/tcp": 3000
webui: "http://[HOST]:[PORT:3000]"
arch:
  - armv7
  - aarch64
  - amd64